### ISSUE TITLE
Not compatible with latest version of Jackson

### ISSUE THREAD

**Issue by redressrtech** [bazaarvoice/rison#5]
Would love to be able to use this with the latest version of Jackson so I can easily embed this in a spring application

**Comment by fakeh** [comment]
It doesn't work with >=2.4. I got it to work with 2.5.3 (I know there's a 2.6 stream already but I'm not targeting that yet, for other reasons) with the following instantiation of RisonFactory: 

		ObjectMapper RISON = new ObjectMapper(new RisonFactory(){
			@Override public boolean canUseCharArrays() {
				return false;
			}
			
			@Override
		    protected RisonParser _createJsonParser(Reader r, IOContext ctxt) throws IOException, JsonParseException {
		        return new RisonParser(ctxt, _parserFeatures, _risonParserFeatures, r, _objectCodec,
		                _rootCharSymbols.makeChild(
		                		(isEnabled(JsonFactory.Feature.CANONICALIZE_FIELD_NAMES) ? JsonFactory.Feature.CANONICALIZE_FIELD_NAMES.getMask() : 0)
		                		|
		                        (isEnabled(JsonFactory.Feature.INTERN_FIELD_NAMES) ? JsonFactory.Feature.INTERN_FIELD_NAMES.getMask() : 0)));
		    }
		});

		String string = "(a:0,b:foo,c:'23skidoo')";
		Map map = RISON.readValue(string, Map.class);
		System.out.println(RISON.writeValueAsString(map));

**Comment by fakeh** [comment]
My changes also work with 2.6.2.

**Comment by Hronom** [comment]
Please add support for the latest version of Jackson - `2.7.2`

**Comment by Hronom** [comment]
I'm trying to maintain updated version here https://github.com/Hronom/jackson-dataformat-rison
Currently it supports latest version 2.9.0, [maven](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.hronom%22%20AND%20a%3A%22jackson-dataformat-rison%22)

**Comment by mike-unitskyi** [comment]
@Hronom check latest releases if it's still valid

**Comment by mike-unitskyi** [comment]
issue has been resolved
